
//15x15
//-1 = black space
//0 = white space
//1-x = numbered space
export const puzzleLoad = [[1,2,3,4,-1,5,6,7,8,-1,9,10,11,12,13],
                            [14,0,0,0,-1,15,0,0,0,-1,16,0,0,0,0],
                            [17,0,0,0,-1,18,0,0,0,-1,19,0,0,0,0],
                            [20,0,0,0,21,0,0,0,0,22,0,-1,23,0,0],
                            [24,0,0,0,0,-1,25,0,0,0,-1,26,0,0,0],
                            [-1,-1,27,0,0,28,0,-1,-1,29,30,0,-1,-1,-1],
                            [31,32,0,-1,-1,33,0,34,-1,35,0,0,36,37,38],
                            [39,0,0,40,41,0,0,0,42,0,0,0,0,0,0],
                            [43,0,0,0,0,0,-1,44,0,0,-1,-1,45,0,0],
                            [-1,-1,-1,46,0,0,-1,-1,47,0,48,49,0,-1,-1],
                            [50,51,52,0,-1,53,54,55,0,-1,56,0,0,57,58],
                            [59,0,0,-1,60,0,0,0,0,61,0,0,0,0,0],
                            [62,0,0,63,0,-1,64,0,0,0,-1,65,0,0,0],
                            [66,0,0,0,0,-1,67,0,0,0,-1,68,0,0,0],
                            [69,0,0,0,0,-1,70,0,0,0,-1,71,0,0,0]];



//First array are acrosses, second are downs
export const clues = [[{number: 1, clue: "DC Donors"},{number: 5, clue: "Old Icelandic Literature"}, 
                       {number: 9, clue: "Himilayan Land"}, {number: 14, clue: "Model Macpherson"}, 
                       {number: 15, clue: "Socially clueless one"}, {number: 16, clue: "Steer clear of"},
                       {number: 17, clue: "Chimney Schmutz"}, {number: 18, clue: "No longer mint"},
                       {number: 19, clue: "Hard-to-combine gas"}, {number: 20, clue: "It may be on the house"},
                       {number: 23, clue: "Paul's 'Exodus' role"}, {number: 24, clue: "Signed, informally"},
                       {number: 25, clue: "Writer Sarah ___ Jewett"}, {number: 26, clue: "Straw in the wind"}, 
                       {number: 27, clue: "Revert to 12:00, say"}, {number: 29, clue: "Mushy food"},
                       {number: 31, clue: "GI address"}, {number: 33, clue: "Numeral in a Uris title"},
                       {number: 35, clue: "Inpenetrable, in a way"},{number: 39, clue: "Brief bio, maybe"},
                       {number: 43, clue: "San ___ (site of Hearst's castle)"},{number: 44, clue: "Prefix with dermis"},
                       {number: 45, clue: "Clerical vestment"},{number: 46, clue: "Target for a quarterback"},
                       {number: 47, clue: "Obie contender"}, {number: 50, clue: "Issue a caveat to"},
                       {number: 53, clue: "Rebuke from Caeser"}, {number: 56, clue: "Straight: Prefix"},
                       {number: 59, clue: "Lacto-___-vegetarian"},{number: 60, clue: "Daniel Boone, for one"},
                       {number: 62, clue: "Sal of 'Rebel Without a Cause'"},{number: 64, clue: "1997 role for Fonda"},
                       {number: 65, clue: "Triangle tone"},{number: 66, clue: "Little green man"},
                       {number: 67, clue: "Kennel guests"},{number: 68, clue: "Sicilian spewer"},
                       {number: 69, clue: "Fran Drescher role"},{number: 70, clue: "Flying 'A' competitor"},
                       {number: 71, clue: "Penn name?"}],
                       //Down
                       [{number: 1, clue: "Joe of 'GoodFellas'"}, {number: 2, clue: "Crazy as ___"},
                       {number: 3, clue: "Legislative-chamber adjunct"}, {number: 4, clue: "Couch potato's perch"},
                       {number: 5, clue: "Sufficient, slangily"}, {number: 6, clue: "Like Stalin"},
                       {number: 7, clue: "Bleak, in verse"}, {number: 8, clue: "Contribute to the mix"},
                       {number: 9, clue: "Barbershop call"}, {number: 10, clue: "Party time, perhaps"},
                       {number: 11, clue: "Airline that flew Clippers, for short"}, {number: 12, clue: "Be gaga over"},  
                       {number: 13, clue: "1917 revolution leader"}, {number: 21, clue: "'___ bodkins!'"},
                       {number: 22, clue: "Patronizing, in a way"}, {number: 26, clue: "Autumn birthstone"},
                       {number: 28, clue: "Former ring champ Holyfield"}, {number: 30, clue: "NYPD broadcast"},
                       {number: 31, clue: "Sit-ups strengthen them"}, {number: 32, clue: "Islands dish"},
                       {number: 34, clue: "Five-star nickname"}, {number: 36, clue: "Metamorphosed sandstone"},
                       {number: 37, clue: "http://www.macnamarasband.com, e.g."}, {number: 38, clue: "Drop in the tide"},
                       {number: 40, clue: "Sharp as a tack"}, {number: 41, clue: "Rock's Bon Jovi"},
                       {number: 42, clue: "Uniform adornments"}, {number: 48, clue: "'My mama done ___ me...'"},
                       {number: 49, clue: "Speaks from the soapbox"}, {number: 50, clue: "Nonvoter before 1920"},
                       {number: 51, clue: "St. Theresa's birthplace"}, {number: 52, clue: "De Niro film of '98"},
                       {number: 54, clue: "Hosiery shade"}, {number: 55, clue: "Pagoda roofing materials"},
                       {number: 57, clue: "Salon tint"}, {number: 58, clue: "Heart, but not soul"},
                       {number: 60, clue: "Cereal-huckstering feline"}, {number: 61, clue: "Anka's 'Eso___'"},
                       {number: 63, clue: "Bard's nightfall"}]];


export const answers = [['P','A','C','S',0,'E','D','D','A',0,'N','E','P','A','L'],
                        ['E','L','L','E',0,'N','E','R','D',0,'E','V','A','D','E'],
                        ['S','O','O','T',0,'U','S','E','D',0,'X','E','N','O','N'],
                        ['C','O','A','T','O','F','P','A','I','N','T',0,'A','R','I'],
                        ['I','N','K','E','D',0,'O','R','N','E',0,'O','M','E','N'],
                        [0,0,'R','E','S','E','T',0,0,'P','A','P',0,0,0],
                        ['A','P','O',0,0,'V','I','I',0,'O','P','A','Q','U','E'],
                        ['B','O','O','K','J','A','C','K','E','T','B','L','U','R','B'],
                        ['S','I','M','E','O','N',0,'E','P','I',0,0,'A','L','B'],
                        [0,0,0,'E','N','D',0,0,'A','C','T','O','R',0,0],
                        ['W','A','R','N',0,'E','T','T','U',0,'O','R','T','H','O'],
                        ['O','V','O',0,'T','R','A','I','L','B','L','A','Z','E','R'],
                        ['M','I','N','E','O',0,'U','L','E','E',0,'T','I','N','G'],
                        ['A','L','I','E','N',0,'P','E','T','S',0,'E','T','N','A'],
                        ['N','A','N','N','Y',0,'E','S','S','O',0,'S','E','A','N']]